spring:
    application:
        name: SmartKitchen
    datasource:
        driverClassName: org.postgresql.Driver
        url: 
        username: 
        password: 
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
        generate-ddl: true
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
token:
    secret: 
    lifetime: 
cloud:
    aws:
        credentials:
            access-key: 
            secret-key: 
        bucket:
            name: 
        endpoint: 
        region: 
