spring:
    application:
        name: SmartKitchen
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://ep-aged-resonance-a2a0q6ds.eu-central-1.aws.neon.tech/SmartKitchen
        username: Semenov
        password: 1mzn8wpBZHbA
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
        generate-ddl: true
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
token:
    secret: zazhgitushinasriismoyivetomvsyanaukachrobvidetbukvimiliymoysumeygovnosmeniitmochoiidirabotaisuka
    lifetime: 864000000
image-path: \src\main\resources\images\